version: '3'
services:
  service:
    build: ./service
    ports: 
      - "5000:5000"
    hostname: service
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    links: 
      - service
      - grafana
    depends_on:
      - service
      - grafana
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"